function(cuda_library)
    set(oneValueArgs TARGET TYPE)
    set(multiValueArgs SRCS INCLUDES DEPS)
    cmake_parse_arguments(ARG "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    if(ARG_TYPE)
        add_library(${ARG_TARGET} ${ARG_TYPE} ${ARG_SRCS})
    else()
        add_library(${ARG_TARGET} ${ARG_SRCS})
    endif()

    # 2. Link the required libraries (User libs + CUDA Runtime + GTest)
    if(ARG_DEPS)
        target_link_libraries(${ARG_TARGET} PUBLIC ${ARG_DEPS})
    endif()
    if(ARG_INCLUDES)
        target_include_directories(${ARG_TARGET} PUBLIC ${ARG_INCLUDES})
    endif()

endfunction()